name: kemo-armillary
description: 'Complete Armillary development environment'
displayName: Kemo Armillary
icon: https://raw.githubusercontent.com/devfile-samples/devfile-stack-icons/main/golang.svg
versions:
  - version: 1.0.1
    default: true
  - version: 1.0.0
